### PR TITLE
Feature groupchat info

### PR DESCRIPTION
**Pull request by lukasHoel**
Wait for READY TO MERGE

### CODE REVIEW

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by lukasHoel** [comment]
TODO:

Editable Description 
                ...color is blue
                ...multiple lines of text do not resize properly
Editable Name and Description
                ...gets always toUppercase?!
Editable Name
               ...may grow bigger than the screen allows if the name is very long
Design
                ...better way than white background and edit-pen to indicate editability needed?
Translation
                ...add to this class (ModalInput values, see ProfileScreen.js)

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=feature-groupchat-info

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by lukasHoel** [comment]
@Totenfluch bitte mergen

**Pull request merged**
