### PR TITLE
AddMember to Group Functionality

### PR DESCRIPTION
**Pull request by Icheler**

### CODE REVIEW

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=f-feature-addmember-screens

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by owlilicious** [comment]
zusätzlich zu Lukas..
- Man kann Leute öfters als einmal hinzufügen (nicht in jeder Gruppe aber in manchen geht es)
- Ich habe 8 Leute in der Gruppe aber es werden 6 Mitglieder angezeigt
- in manchen Gruppen kann man (als nicht admin) hinzufügen, es wird im Chat angezeigt(System true message), aber die Leute werden nicht in der Mitgliederliste angezeigt

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=f-feature-addmember-screens

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by lukasHoel** [comment]
Du hast die Expo settings committed..

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=f-feature-addmember-screens

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=f-feature-addmember-screens

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Comment by Totenfluch** [comment]
:shipit: This branch has been deployed to:
  https://expo.io/@hschat/hschat?release-channel=f-feature-addmember-screens

  Download the [Expo](https://expo.io/) app and scan this QR code to get started!

  QR Code

**Pull request merged**
